server:
  port: 9090
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:analyzerdb}
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

api-url: "https://api.telegram.org/"
webhook-path: "https://5a14-92-124-163-91.eu.ngrok.io"
bot-name: "StockManager22Bot"
bot-token: "5338435964:AAF0Uh_K8czaegmS_PFKLjKpcOqgX5Vj4CA"
